// Minerva City Rotation Data — Academic Year 2025–26
const CITIES = [
  {
    id: "sf",
    name: "San Francisco",
    country: "USA",
    flag: "🇺🇸",
    emoji: "🌉",
    semester: "Fall — Semester 1",
    dates: { start: "Aug 25, 2025", end: "Dec 12, 2025" },
    color: "#C2724F",          // Clay
    tagline: "Where it all begins",
    description: "Home base. San Francisco anchors the Minerva experience with its culture of innovation, access to the tech industry, and diverse urban environment. Students take foundational HC courses and begin community life.",
    highlights: [
      "Exploratorium visits & science communication",
      "Mission District community immersion",
      "Tech company site visits (optional)",
      "Golden Gate Park weekend markets",
    ],
    deadlines: [
      { label: "Housing selection form", date: "Jul 15, 2025" },
      { label: "Fall course enrollment", date: "Aug 1, 2025" },
      { label: "Health insurance verification", date: "Aug 20, 2025" },
    ],
    resources: [
      { label: "SF Student Guide (PDF)", url: "#" },
      { label: "Housing Portal", url: "#" },
    ],
    tips: "Pack layers — SF weather is famously unpredictable. BART card is your best friend.",
  },
  {
    id: "seoul",
    name: "Seoul",
    country: "South Korea",
    flag: "🇰🇷",
    emoji: "🏙️",
    semester: "Spring — Semester 2",
    dates: { start: "Jan 12, 2026", end: "May 8, 2026" },
    color: "#3B82A0",
    tagline: "Innovation meets tradition",
    description: "Seoul blends cutting-edge technology with deep cultural heritage. Students engage with Korea's design, policy, and business scenes, taking courses with a focus on social systems and cultural perspectives.",
    highlights: [
      "DMZ educational visit",
      "Hanok Village urban history walk",
      "K-startup ecosystem tours",
      "Temple Stay weekend (optional)",
    ],
    deadlines: [
      { label: "Korean visa application", date: "Nov 20, 2025" },
      { label: "Spring course enrollment", date: "Dec 5, 2025" },
      { label: "Flight booking window", date: "Dec 10, 2025" },
    ],
    resources: [
      { label: "Seoul Student Guide (PDF)", url: "#" },
      { label: "Visa Application Help", url: "#" },
    ],
    tips: "Download Naver Maps — Google Maps has limited functionality in Korea. T-money card for transit.",
  },
  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    flag: "🇩🇪",
    emoji: "🏛️",
    semester: "Fall — Semester 3",
    dates: { start: "Aug 31, 2026", end: "Dec 18, 2026" },
    color: "#6B7280",
    tagline: "History, politics & art",
    description: "Berlin confronts students with Europe's complex 20th-century history while immersing them in one of the world's most dynamic arts and political scenes. HC courses here focus on civic institutions and critical theory.",
    highlights: [
      "Reichstag & parliamentary visit",
      "Memorial to the Murdered Jews of Europe",
      "Berlin Biennale (if timing aligns)",
      "Techno culture deep-dive (optional)",
    ],
    deadlines: [
      { label: "Schengen visa (if required)", date: "Jun 15, 2026" },
      { label: "Fall 3 course enrollment", date: "Jul 1, 2026" },
    ],
    resources: [
      { label: "Berlin Student Guide (PDF)", url: "#" },
      { label: "EU Schengen Info", url: "#" },
    ],
    tips: "Berlin is huge — get a monthly BVG transit pass. Many places are cash-only.",
  },
  {
    id: "buenosaires",
    name: "Buenos Aires",
    country: "Argentina",
    flag: "🇦🇷",
    emoji: "💃",
    semester: "Spring — Semester 4",
    dates: { start: "Jan 11, 2027", end: "May 7, 2027" },
    color: "#84A87A",
    tagline: "Passion, politics & creativity",
    description: "Buenos Aires offers a rich lens into Latin American culture, economics, and politics. Students engage with local communities, take Spanish immersion intensives, and study themes of democracy and inequality.",
    highlights: [
      "Tango class & cultural exchange",
      "La Boca neighbourhood community project",
      "Economic history walking tour",
      "Weekend trips to the Pampas or Patagonia",
    ],
    deadlines: [
      { label: "Argentina entry requirements check", date: "Nov 15, 2026" },
      { label: "Spring 4 enrollment", date: "Dec 1, 2026" },
    ],
    resources: [
      { label: "BA Student Guide (PDF)", url: "#" },
    ],
    tips: "Learn basic Spanish before arriving — it transforms the experience. Always carry pesos for smaller shops.",
  },
  {
    id: "london",
    name: "London",
    country: "UK",
    flag: "🇬🇧",
    emoji: "🎡",
    semester: "Fall — Semester 5",
    dates: { start: "Sep 7, 2027", end: "Dec 16, 2027" },
    color: "#8B5CF6",
    tagline: "Global finance & culture",
    description: "London connects students to global finance, policy, media, and the arts. The city's multicultural fabric and world-class institutions make it a hub for professional exploration and intercultural dialogue.",
    highlights: [
      "Parliament & policy briefings",
      "Tate Modern gallery visits",
      "City of London finance district tour",
      "East End cultural walk",
    ],
    deadlines: [
      { label: "UK student visa (Tier 4)", date: "Jun 1, 2027" },
      { label: "Fall 5 enrollment", date: "Jul 15, 2027" },
    ],
    resources: [
      { label: "London Student Guide (PDF)", url: "#" },
    ],
    tips: "Oyster card for the Tube. The NHS walk-in clinics are free for students — register early.",
  },
  {
    id: "hyderabad",
    name: "Hyderabad",
    country: "India",
    flag: "🇮🇳",
    emoji: "🕌",
    semester: "Spring — Semester 6",
    dates: { start: "Jan 10, 2028", end: "May 5, 2028" },
    color: "#D97706",
    tagline: "Tech, tradition & scale",
    description: "The final rotation brings students to one of India's fastest-growing tech hubs. Hyderabad balances Mughal heritage with a booming startup scene, offering a capstone experience centred on scale, impact, and complexity.",
    highlights: [
      "HITEC City startup ecosystem visits",
      "Charminar & old city immersion",
      "Social enterprise visits in surrounding districts",
      "Capstone project presentations",
    ],
    deadlines: [
      { label: "Indian student visa application", date: "Nov 1, 2027" },
      { label: "Capstone topic submission", date: "Nov 15, 2027" },
      { label: "Spring 6 enrollment", date: "Dec 1, 2027" },
    ],
    resources: [
      { label: "Hyderabad Student Guide (PDF)", url: "#" },
    ],
    tips: "Hyderabad summers are intense — hydrate constantly. Auto-rickshaws use meters; insist on them.",
  },
];

// Default deadlines (shared across all views)
const DEFAULT_DEADLINES = [
  { id: "d1", title: "Apply for financial aid renewal", city: "", date: "2025-07-01", system: true },
  { id: "d2", title: "SF housing selection form", city: "sf", date: "2025-07-15", system: true },
  { id: "d3", title: "Fall course enrollment opens", city: "sf", date: "2025-08-01", system: true },
  { id: "d4", title: "Korean visa application deadline", city: "seoul", date: "2025-11-20", system: true },
  { id: "d5", title: "Spring course enrollment (Seoul)", city: "seoul", date: "2025-12-05", system: true },
];
