// Minerva City Rotation Data — 4-Year Program
const CITIES = [
  {
    id: "sf",
    name: "San Francisco",
    country: "USA",
    flag: "🇺🇸",
    emoji: "🌉",
    semester: "Year 1",
    dates: { start: "Aug 25, 2025", end: "May 15, 2026" },
    color: "#C2724F",
    tagline: "Where it all begins",
    description: "Home base. San Francisco anchors the Minerva experience with its culture of innovation, access to the tech industry, and diverse urban environment. Students take foundational courses and begin community life in one of the world's most dynamic cities.",
    highlights: [
      "Exploratorium visits & science communication",
      "Mission District community immersion",
      "Tech company site visits (optional)",
      "Golden Gate Park weekend markets",
    ],
    deadlines: [
      { label: "Housing selection form", date: "Jul 15, 2025" },
      { label: "Year 1 course enrollment", date: "Aug 1, 2025" },
      { label: "Health insurance verification", date: "Aug 20, 2025" },
    ],
    resources: [
      { label: "SF Student Guide (PDF)", url: "#" },
      { label: "Housing Portal", url: "#" },
    ],
    tips: "Pack layers — SF weather is famously unpredictable. BART card is your best friend.",
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    flag: "🇯🇵",
    emoji: "🗼",
    semester: "Year 2",
    dates: { start: "Aug 24, 2026", end: "May 14, 2027" },
    color: "#E05C8A",
    tagline: "Precision, culture & the future",
    description: "Tokyo immerses students in one of the world's most efficient and culturally rich cities. From ancient temples to cutting-edge robotics, students engage with Japan's unique synthesis of tradition and technological innovation across both semesters.",
    highlights: [
      "teamLab digital art immersion",
      "Tsukiji market & food culture deep-dive",
      "Robot café & AI lab visits",
      "Kyoto day trip — Fushimi Inari & Arashiyama",
    ],
    deadlines: [
      { label: "Japan student visa application", date: "Jun 1, 2026" },
      { label: "Year 2 course enrollment", date: "Jul 1, 2026" },
      { label: "Flight booking window opens", date: "Jul 15, 2026" },
    ],
    resources: [
      { label: "Tokyo Student Guide (PDF)", url: "#" },
      { label: "Japan Visa Help", url: "#" },
    ],
    tips: "Get a Suica card for transit — it works everywhere. Download Google Translate with Japanese offline pack before you land.",
  },
  {
    id: "buenosaires",
    name: "Buenos Aires",
    country: "Argentina",
    flag: "🇦🇷",
    emoji: "💃",
    semester: "Year 3",
    dates: { start: "Aug 23, 2027", end: "May 12, 2028" },
    color: "#84A87A",
    tagline: "Passion, politics & creativity",
    description: "Buenos Aires offers a rich lens into Latin American culture, economics, and politics. Students engage with local communities, take Spanish immersion intensives, and study themes of democracy and inequality across one of South America's most vibrant capitals.",
    highlights: [
      "Tango class & cultural exchange",
      "La Boca neighbourhood community project",
      "Economic history walking tour",
      "Weekend trips to the Pampas or Patagonia",
    ],
    deadlines: [
      { label: "Argentina entry requirements check", date: "Jun 1, 2027" },
      { label: "Year 3 course enrollment", date: "Jul 1, 2027" },
      { label: "Spanish placement test", date: "Aug 1, 2027" },
    ],
    resources: [
      { label: "Buenos Aires Student Guide (PDF)", url: "#" },
      { label: "Spanish Prep Resources", url: "#" },
    ],
    tips: "Learn basic Spanish before arriving — it transforms the experience. Always carry pesos for smaller shops.",
  },
  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    flag: "🇩🇪",
    emoji: "🏛️",
    semester: "Year 4",
    dates: { start: "Aug 28, 2028", end: "May 17, 2029" },
    color: "#6B7280",
    tagline: "History, politics & your capstone",
    description: "The final year brings students to Berlin — a city that confronts Europe's complex 20th-century history while hosting one of the world's most dynamic arts and political scenes. Year 4 is anchored by the capstone project and professional immersion.",
    highlights: [
      "Reichstag & parliamentary visit",
      "Memorial to the Murdered Jews of Europe",
      "Berlin Biennale (if timing aligns)",
      "Capstone project presentations & graduation prep",
    ],
    deadlines: [
      { label: "Schengen visa (if required)", date: "Jun 1, 2028" },
      { label: "Year 4 course enrollment", date: "Jul 1, 2028" },
      { label: "Capstone topic submission", date: "Sep 15, 2028" },
      { label: "Capstone first draft", date: "Feb 1, 2029" },
    ],
    resources: [
      { label: "Berlin Student Guide (PDF)", url: "#" },
      { label: "EU Schengen Info", url: "#" },
      { label: "Capstone Guidelines", url: "#" },
    ],
    tips: "Berlin is huge — get a monthly BVG transit pass. Many places are cash-only. Start your capstone early.",
  },
];

// Default deadlines
const DEFAULT_DEADLINES = [
  { id: "d1", title: "Apply for financial aid renewal", city: "", date: "2025-07-01", system: true },
  { id: "d2", title: "SF housing selection form", city: "sf", date: "2025-07-15", system: true },
  { id: "d3", title: "Year 1 course enrollment opens", city: "sf", date: "2025-08-01", system: true },
  { id: "d4", title: "Japan student visa application", city: "tokyo", date: "2026-06-01", system: true },
  { id: "d5", title: "Year 2 course enrollment (Tokyo)", city: "tokyo", date: "2026-07-01", system: true },
  { id: "d6", title: "Argentina entry requirements check", city: "buenosaires", date: "2027-06-01", system: true },
  { id: "d7", title: "Capstone topic submission (Berlin)", city: "berlin", date: "2028-09-15", system: true },
];
